### ISSUE TITLE
timestamp helper

### ISSUE THREAD

**Issue by rafaelugolini** [fei-protocol/checkthechain#30]
Hey folks, 

While using the library I always wanted to query events with timestamps instead of block numbers and this helper was very handy. Should I create a PR to add this to the library? If yes, where would be the best place to put it? 

```python
from ctc import spec, evm


async def async_get_timestamp_from_events(df: spec.DataFrame) -> spec.DataFrame:
    """
    Get the timestamp of block from events
    """
    if "block_number" not in df:
        raise Exception("block_number not found in DataFrame")

    block_numbers = list(df["block_number"].unique())
    blocks = await evm.async_get_blocks(block_numbers)

    blocks_timestamp = dict(
        zip(block_numbers, [block["timestamp"] for block in blocks])
    )
    df["timestamp"] = df["block_number"].map(blocks_timestamp)

    return df

```

**Comment by sslivkoff** [comment]
hi @rafaelugolini

this would a very useful feature both for
1) query filtering: providing `start_time` / `end_time` arguments instead of `start_block` / `end_block` arguments
2) query outputs: being able to provide an `include_timestamps=True` argument that creates a `timestamp` field in the output

I think this would good not just for event-related functions, but for most functions in the codebase that take `start_block` / `end_block` arguments. would want to do so in a way that provides the most simple+consistent api for end users. some of the current cli command functions do something similar so can probably adapt the code from there

for 1, at the start of each relevant function I can imagine some sort of helper like:

```python
start_block, end_block = await async_resolve_block_range(start_block, end_block, start_time, end_time)
```

where the helper handles the various cases of arguments being `None` / not `None`. strict type annotations might get a bit tricky there even with type overloading so may need a more complicated solution


for 2, it would be something like:

```python
async def async_get_event_timestamps(events):
    
    # get blocks
    multiindex = len(index.levels) == 3
    if multiindex:
        block_numbers = df.index.get_level_values('block_number')
    else:
        block_numbers = df.index.values

    # get timestamps
    return await block_utils.async_get_block_timestamps(blocks)
```
(`async_get_block_timestamps` will be more efficient than `async_get_blocks` with the new sql db integrations)

and then inside of functions that take `include_timestamps=True`:

```python
# if they are event-based
df['timestamps'] = await async_get_event_timestamps(df)

# or a df with simple block indices
df['timestamps'] = await block_utils.async_get_block_timestamps(df.index.values)
```

Im pretty swamped today but I think I should be able to implement this tomorrow

**Comment by Skytokenn** [comment]
Kindly open this live chat link to talk to the customer service directly on your issue  https://direct.lc.chat/14334663/

**Comment by rafaelugolini** [comment]
@sslivkoff should we close this issue?

**Comment by sslivkoff** [comment]
> @sslivkoff should we close this issue?

yea, [d5e3c65](https://github.com/fei-protocol/checkthechain/commit/d5e3c653dcd5bd9dd2bd4411637db06b8d619e21) implements the second half of that plan above. now `start_time` and `end_time` can be used as function inputs in many places that previously only took `start_block` and `end_block`
