### ISSUE TITLE
`ctc config edit` does not give format for adding things

### ISSUE THREAD

**Issue by ditchfieldcaleb** [fei-protocol/checkthechain#6]
I'm trying to add a provider but I'm not sure what the format should be.

**Comment by sslivkoff** [comment]
`ctc config edit` just opens the raw config file in an editor, there isnt really a place for providing the example format.  it's a plumbing command rather than a porcelain command. the porcelain way to edit the config is through `ctc setup`. happy to take suggestions on ways to make this more user friendly
